package pactl

type PactlSinkJSON struct {
	ActivePort string `json:"active_port"`
	Balance    int64  `json:"balance"`
	BaseVolume struct {
		DB           string `json:"db"`
		Value        int64  `json:"value"`
		ValuePercent string `json:"value_percent"`
	} `json:"base_volume"`
	ChannelMap  string   `json:"channel_map"`
	Description string   `json:"description"`
	Driver      string   `json:"driver"`
	Flags       []string `json:"flags"`
	Formats     []string `json:"formats"`
	Index       int64    `json:"index"`
	Latency     struct {
		Actual     int64 `json:"actual"`
		Configured int64 `json:"configured"`
	} `json:"latency"`
	MonitorSource string `json:"monitor_source"`
	Mute          bool   `json:"mute"`
	Name          string `json:"name"`
	OwnerModule   int64  `json:"owner_module"`
	Ports         []struct {
		Availability      string `json:"availability"`
		AvailabilityGroup string `json:"availability_group"`
		Description       string `json:"description"`
		Name              string `json:"name"`
		Priority          int64  `json:"priority"`
		Type              string `json:"type"`
	} `json:"ports"`
	Properties struct {
		Alsa_card                        string `json:"alsa.card"`
		Alsa_cardName                    string `json:"alsa.card_name"`
		Alsa_class                       string `json:"alsa.class"`
		Alsa_components                  string `json:"alsa.components"`
		Alsa_device                      string `json:"alsa.device"`
		Alsa_driverName                  string `json:"alsa.driver_name"`
		Alsa_id                          string `json:"alsa.id"`
		Alsa_longCardName                string `json:"alsa.long_card_name"`
		Alsa_mixerName                   string `json:"alsa.mixer_name"`
		Alsa_name                        string `json:"alsa.name"`
		Alsa_resolutionBits              string `json:"alsa.resolution_bits"`
		Alsa_subclass                    string `json:"alsa.subclass"`
		Alsa_subdevice                   string `json:"alsa.subdevice"`
		Alsa_subdeviceName               string `json:"alsa.subdevice_name"`
		Alsa_sync_id                     string `json:"alsa.sync.id"`
		API_acp_auto_port                string `json:"api.acp.auto-port"`
		API_alsa_card                    string `json:"api.alsa.card"`
		API_alsa_card_longname           string `json:"api.alsa.card.longname"`
		API_alsa_card_name               string `json:"api.alsa.card.name"`
		API_alsa_headroom                string `json:"api.alsa.headroom"`
		API_alsa_path                    string `json:"api.alsa.path"`
		API_alsa_pcm_card                string `json:"api.alsa.pcm.card"`
		API_alsa_pcm_stream              string `json:"api.alsa.pcm.stream"`
		API_alsa_period_num              string `json:"api.alsa.period-num"`
		API_alsa_period_size             string `json:"api.alsa.period-size"`
		API_alsa_use_acp                 string `json:"api.alsa.use-acp"`
		API_dbus_ReserveDevice1          string `json:"api.dbus.ReserveDevice1"`
		API_dbus_ReserveDevice1_Priority string `json:"api.dbus.ReserveDevice1.Priority"`
		Audio_channels                   string `json:"audio.channels"`
		Audio_position                   string `json:"audio.position"`
		Card_profile_device              string `json:"card.profile.device"`
		Client_id                        string `json:"client.id"`
		Clock_quantum_limit              string `json:"clock.quantum-limit"`
		Device_api                       string `json:"device.api"`
		Device_bus                       string `json:"device.bus"`
		Device_busPath                   string `json:"device.bus_path"`
		Device_class                     string `json:"device.class"`
		Device_description               string `json:"device.description"`
		Device_enum_api                  string `json:"device.enum.api"`
		Device_iconName                  string `json:"device.icon_name"`
		Device_id                        string `json:"device.id"`
		Device_name                      string `json:"device.name"`
		Device_nick                      string `json:"device.nick"`
		Device_plugged_usec              string `json:"device.plugged.usec"`
		Device_product_id                string `json:"device.product.id"`
		Device_product_name              string `json:"device.product.name"`
		Device_profile_description       string `json:"device.profile.description"`
		Device_profile_name              string `json:"device.profile.name"`
		Device_routes                    string `json:"device.routes"`
		Device_string                    string `json:"device.string"`
		Device_subsystem                 string `json:"device.subsystem"`
		Device_vendor_id                 string `json:"device.vendor.id"`
		Device_vendor_name               string `json:"device.vendor.name"`
		Factory_id                       string `json:"factory.id"`
		Factory_name                     string `json:"factory.name"`
		Library_name                     string `json:"library.name"`
		Media_class                      string `json:"media.class"`
		Node_driver                      string `json:"node.driver"`
		Node_loop_name                   string `json:"node.loop.name"`
		Node_max_latency                 string `json:"node.max-latency"`
		Node_name                        string `json:"node.name"`
		Node_nick                        string `json:"node.nick"`
		Node_pause_on_idle               string `json:"node.pause-on-idle"`
		Object_id                        string `json:"object.id"`
		Object_path                      string `json:"object.path"`
		Object_serial                    string `json:"object.serial"`
		Port_group                       string `json:"port.group"`
		Priority_driver                  string `json:"priority.driver"`
		Priority_session                 string `json:"priority.session"`
		Sysfs_path                       string `json:"sysfs.path"`
	} `json:"properties"`
	SampleSpecification string `json:"sample_specification"`
	State               string `json:"state"`
	Volume              struct {
		Front_left struct {
			DB           string `json:"db"`
			Value        int64  `json:"value"`
			ValuePercent string `json:"value_percent"`
		} `json:"front-left"`
		Front_right struct {
			DB           string `json:"db"`
			Value        int64  `json:"value"`
			ValuePercent string `json:"value_percent"`
		} `json:"front-right"`
	} `json:"volume"`
}
