name: Audit

on:
  push:
    branches: [dev]
  pull_request:
    branches: [dev]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  analyze:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Go
        uses: jdx/mise-action@v2

      # Only for DEBUGING with remote shell
      # - name: Setup upterm session
      #   uses: lhotari/action-upterm@v1

      - name: Audit
        run: |
          mise install
          make audit/ci
