name: release
on:
  push:
    tags:
      - "*"

jobs:
  build_release:
    name: Build_release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: "1.22.4" # Ensure this matches your local version

      # - name: Run staticcheck
      #   run: go run honnef.co/go/tools/cmd/staticcheck@latest -checks=all,-ST1000,-U1000 ./... --debug.version
      - name: Audit
        run: make audit
      - name: Build
        run: |
          go get -t ./...
          go build -o prapi
          zip -r "/tmp/bin/prapi-$GITHUB_REF_NAME.zip" prapi
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            /tmp/bin/prapi-${{ github.ref_name }}.zip
            /tmp/bin/prapi
