name: release
on:
  push:
    tags:
      - "*"

jobs:
  build_release:
    name: Build_release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: "1.22.4" # Ensure this matches your local version
      # - name: Audit
      #   run: make audit
      - name: Build
        run: |
          echo "ghref: $GITHUB_REF_NAME"
          go get -t ./...
          go build -o prapi
          echo "[zip]"
          zip -r "prapi-$GITHUB_REF_NAME.zip" prapi
          echo "[ls]"
          ls
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            ./prapi-${{ github.ref_name }}.zip
            ./prapi
