name: Test(pulseaudio)

on:
  push:
    branches: [dev]
  pull_request:
    branches: [dev]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  PULSE_SERVER: unix:/tmp/pulse-socket

jobs:
  Test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: jdx/mise-action@v2

      - name: Setup PulseAudio
        run: |
          sudo apt-get update
          sudo apt-get install -y pulseaudio
          pulseaudio --start --exit-idle-time=-1
          sleep 5
          pactl load-module module-null-sink
          pactl list short sinks

      - name: Run tests
        run: make test
