name: Test(pipewire)

on:
  push:
    branches: [dev]
  pull_request:
    branches: [dev]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  Test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install pactl
        run: |
          sudo apt-get update
          sudo apt-get install -y pipewire pipewire-pulse

      - name: Test
        run: make test
