name: Test(pipewire)

on:
  push:
    branches: [dev]
  pull_request:
    branches: [dev]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  Test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Test pipewire
        run: |
          # install and start pipewire
          sudo apt-get update
          sudo apt-get install -y pipewire pulseaudio
          systemctl --user start pipewire
          pactl load-module module-null-sink
          # run test
          make test

