name: Test(pulseaudio)

on:
  push:
    branches: [dev]
  pull_request:
    branches: [dev]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  Test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Go
        uses: jdx/mise-action@v2

      - name: Setup upterm session
        uses: lhotari/action-upterm@v1
      
      - name: Test pulseaudio
        run: |
          # install and start pulseaudio
          sudo apt-get update 
          sudo apt-get install -y pulseaudio
          pulseaudio --start
          # sleep 10
          # load virtual audio device
          # pactl load-module module-null-sink
          # run test
          make test
